GuitarShopD/GuitarShopD/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace GuitarShopD.Controllers
{
    
    public class HomeController : Controller
    {
       

        public ActionResult Index()
        {
            var context = new GSDEVEntities();
            List<Category> categories = new List<Category>();
            foreach (Category c in context.Categories)
            {
                if(c.ParentID == null)
                    categories.Add(c);
            }
            return View(categories);
        }
        public ActionResult CategoryDirect(string id)
        {
            var context = new GSDEVEntities();
            List<Category> categories = new List<Category>();
            foreach (Category c in context.Categories)
            {
                if (c.ParentID.ToString() == id)
                    categories.Add(c);
            }
            return View("CategoryDirect", categories);
        }

        public ActionResult SubCategoryDirect(string id)
        {
            var context = new GSDEVEntities();
            List<Purpose> purpose = new List<Purpose>();
            foreach (Purpose p in context.Purposes)
            {

                if (p.Item.CategoryID.ToString() == id)
                {
                    purpose.Add(p);
                    ViewBag.console = "" + p.Item.Category.Name.ToString();
                }
            }
            return View("SubCategoryDirect", purpose);
        }
    }
}

GuitarShopD/GuitarShopD/Controllers/ItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GuitarShopD.Controllers
{
    public class ItemController : Controller
    {
        // GET: Item
        public ActionResult GetItem(string id)
        {
            var context = new GSDEVEntities();
            var purposeList = context.purposePrices;
            var currentPurpose = from current in purposeList
                                 where current.Purpose.id.ToString() == id
                                 select current;
            return View(currentPurpose);
        }
    }
}

GuitarShopD/GuitarShopD/Views/Home/CategoryDirect.cshtml
@{
    //Layout = null;
}

<!DOCTYPE html>

<html>
<body>
    <div id="container">

        <main id="center" class="column">
            <article>

                <h1>News</h1>
                <h3>News name</h3>
                <h5>data</h5>
                Ipsum gravida vel pretium tellus tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut.
                Velit mollis odio sollicitudin lacinia aliquam posuere, sapien elementum lobortis tincidunt, turpis dui ornare nisl, sollicitudin interdum turpis nunc eget sem nulla eu ultricies orci praesent id augue nec lorem pretium congue sit amet ac nunc fusce iaculis lorem eu diam hendrerit at mattis purus dignissim vivamus mauris tellus, fringilla vel dapibus a, blandit quis erat vivamus elementum aliquam luctus etiam fringilla pretium sem vitae sodales mauris id nulla est praesent laoreet, metus vel auctor aliquam, eros purus vulputate leo, eget consequat neque quam id tellus duis ultricies tempor tortor, vitae dignissim ligula mattis nec in hac habitasse platea dictumst.
            </article>
        </main>

        <nav id="left" class="column">
            <h3>Sub Categories</h3>
            @foreach (Category category in Model)
            {
                <p>@Html.ActionLink("" + category.Name, "SubCategoryDirect", "Home", new { id = category.id.ToString() }, null)</p>
            }
        </nav>

        <div id="right" class="column">
            <h3>CART</h3>
            <p>
                X
            </p>
        </div>

    </div>


</body>

</html>

GuitarShopD/GuitarShopD/Views/Home/Index.cshtml
@model  List<Category>

@{
   // Layout = null;
}
<html>
<body>
    <div id="container">
         
        <main id="center" class="column">
            <article>

                <h1>News</h1>
                <h3>News name</h3>
                <h5>data</h5>
                Ipsum gravida vel pretium tellus tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut.
                Velit mollis odio sollicitudin lacinia aliquam posuere, sapien elementum lobortis tincidunt, turpis dui ornare nisl, sollicitudin interdum turpis nunc eget sem nulla eu ultricies orci praesent id augue nec lorem pretium congue sit amet ac nunc fusce iaculis lorem eu diam hendrerit at mattis purus dignissim vivamus mauris tellus, fringilla vel dapibus a, blandit quis erat vivamus elementum aliquam luctus etiam fringilla pretium sem vitae sodales mauris id nulla est praesent laoreet, metus vel auctor aliquam, eros purus vulputate leo, eget consequat neque quam id tellus duis ultricies tempor tortor, vitae dignissim ligula mattis nec in hac habitasse platea dictumst.
            </article>
        </main>

        <nav id="left" class="column">
            <h3>Categories</h3>
            @foreach (Category category in Model)
            {
                    <p>@Html.ActionLink("" + category.Name, "CategoryDirect", "Home", new { id = category.id.ToString() }, null)</p>             
            }
        </nav>

        <div id="right" class="column">
            <h3>CART</h3>
            <p>
               X
            </p>
        </div>

    </div>

    
</body>

</html>

GuitarShopD/GuitarShopD/Views/Home/SubCategoryDirect.cshtml
@model List<Purpose>
@{
    //Layout = null;
}

<!DOCTYPE html>

<html>
<body>
    <div id="container">

        <main id="center" class="column">
            <article>

                <h1>@ViewBag.console</h1>
               
                @foreach (Purpose purpose in Model)
                 {
                    
                    <p>@Html.ActionLink("" + purpose.Item.Brand.Name + " "+ purpose.Item.Name+" Price: "+ purpose.purposePrices.Last().price, "GetItem", "Item", new { id = purpose.id.ToString() }, null)</p>
                }



            </article>
        </main>

        <nav id="left" class="column">
            <h3>Sort</h3>
            <h3>Filters</h3>
         
        </nav>

        <div id="right" class="column">
            <h3>CART</h3>
            <p>
                X
            </p>
        </div>

    </div>
</body>

</html>

GuitarShopD/GuitarShopD/Views/Item/GetItem.cshtml
@{
    //Layout = null;
}
<!DOCTYPE html>

<html>
<body>
    <div id="container">

        <main id="center" class="column">
            <article>

                <h1>@ViewBag.console</h1>

                @foreach (purposePrice purpose in Model)
                {

                    <h1>@purpose.Purpose.Item.Brand.Name</h1>
                    <h2>@purpose.Purpose.Item.Name</h2>
                    <h3>@purpose.price @purpose.Curency.Name</h3>
                    <p>Availability : @purpose.Purpose.AvailabilityType.Name </p> 
                    <p>@purpose.Purpose.Item.Description</p>
                    <h3>Characteristics :</h3>
                    
                }
            </article>
        </main>

        <nav id="left" class="column">
            

        </nav>

        <div id="right" class="column">
            <h3>CART</h3>
            <p>
                X
            </p>
        </div>

    </div>

</body>

</html>

GuitarShopD/GuitarShopD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<body>

    <header id="header">
        <h1>GUITAR SHOP</h1>
        @Html.ActionLink("Home", "Index", "Home") @Html.ActionLink("Catalog", "Index", "Home") @Html.ActionLink("Delivery and Payment", "Index", "Home") @Html.ActionLink("Contacts", "Index", "Home") @Html.ActionLink("Cart", "Index", "Home")
    </header>
    
    <link rel="stylesheet" type="text/css" href="~/Content/style.css">
           
            @RenderBody()

        <div id="footer-wrapper">
            <footer id="footer"><p>GuitarShop CA</p></footer>
        </div>

</body>
</html>